name: 'Build Container .NET'
description: 'Build and publish Docker-Image'
inputs:
  TAG_PREFIX:
    description: ""
    required: false
    default: "dev_"
  DOCKERHUB_USERNAME:
    description: "The username with which the container will be published to DockerHub."
    required: false
    default: "fedodo"
  DOCKERHUB_TOKEN:
    description: "The token with which the container will be published to DockerHub."
    required: true
  PROJECT_PATH:
    description: "Path to the Test-Project."
    required: true
  REPO:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Test
    - name: "Install .net"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "7.x"

    - name: "Restore packages"
      shell: bash
      run: dotnet restore ${{ inputs.PROJECT_PATH }}

    - name: "Test"
      shell: bash
      run: dotnet test ${{ inputs.PROJECT_PATH }} --no-restore --configuration Release

    # Build
    - name: Build the Docker image
      shell: bash
      run: docker build . --file Dockerfile --tag ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.REPO }}:${{ inputs.TAG_PREFIX }}${{ github.run_number }}

    # Publish
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Push the image to dockerhub
      shell: bash
      run: docker push ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.REPO }}:${{ inputs.TAG_PREFIX }}${{ github.run_number }}