name: 'Build Container Flutter'
description: 'Build and publish Docker-Image'
inputs:
  TAG_PREFIX:
    description: ""
    required: false
    default: "dev_"
  DOCKERHUB_USERNAME:
    description: "The username with which the container will be published to DockerHub."
    required: false
    default: "fedodo"
  DOCKERHUB_TOKEN:
    description: "The token with which the container will be published to DockerHub."
    required: true
  REPO:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: britannio/action-install-flutter@main

    - run: flutter build web --build-number=${{ github.run_number }}
      working-directory: ./
      shell: bash

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: web
        path: ./build/web/

    - name: Build the Docker image
      shell: bash
      run: docker build . --file Dockerfile --tag ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.REPO }}:${{ inputs.TAG_PREFIX }}${{ github.run_number }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Push the image to dockerhub
      shell: bash
      run: docker push ${{ inputs.DOCKERHUB_USERNAME }}/${{ inputs.REPO }}:${{ inputs.TAG_PREFIX }}${{ github.run_number }}