name: Create Action

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
