name: Create Action

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      - name: release
        uses: actions/create-release@v1
        id: Fedodo_Pipelines_BuildContainer_NET
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: V${{ github.run_number }}
#          body_path: ./.github/Changelog.md